version: "3.8"

services:
    # db:
    #     # Debian buster
    #     image: postgres:12
    #     restart: always
    #     ports: 
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_DB: "cldb"
    #         POSTGRES_USER: "postgres"
    #         POSTGRES_PASSWORD: "postgres"
    #     volumes:
    #         - ./.pgdata:/var/lib/postgresql/data

    redis:
        image: redis:6.0-buster
        container_name: redis0
        ports:
            - "6379:6379"
        volumes:
            - ./.redis-data:/var/lib/redis
            - ./.redis-conf:/usr/location/etc/redis/redis.conf

    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: "rbondoc96@gmail.com"
    #         PGADMIN_DEFAULT_PASSWORD: "postgres"
    #         PGADMIN_LISTEN_PORT: "80"
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./.pgadmin-data:/var/lib/pgadmin
    #     links:
    #         - "db:pgsql-server"

    # dev:
    #     build: .
    #     command: python ./cldb/manage.py runserver 0.0.0.0:8000
    #     volumes:
    #         - .:/code
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         - db