# Generated by Django 3.1.3 on 2020-11-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Survivor', 'Survivor'), ('Killer', 'Killer')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EffectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Survivor', 'Survivor'), ('Killer', 'Killer')], max_length=15)),
                ('tier', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
                ('description', models.TextField()),
                ('quote', models.CharField(max_length=255)),
                ('effects', models.ManyToManyField(to='game.Effect', verbose_name='Effects')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('effects', models.ManyToManyField(to='game.Effect', verbose_name='Effects')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.rarity')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.effecttype'),
        ),
        migrations.AddConstraint(
            model_name='perk',
            constraint=models.UniqueConstraint(fields=('name', 'tier'), name='perk_name_tier_key'),
        ),
    ]
