# Generated by Django 3.1.3 on 2020-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effecttype',
            options={'verbose_name': 'Effect Type', 'verbose_name_plural': 'Effect Types'},
        ),
        migrations.AlterField(
            model_name='perk',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
