# Generated by Django 3.1.3 on 2020-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201110_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'ordering': ['type']},
        ),
        migrations.AddField(
            model_name='effect',
            name='affects_all',
            field=models.BooleanField(default=False, verbose_name='Does the Effect affect ALL players?'),
        ),
    ]
