# Generated by Django 3.1.3 on 2020-11-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20201110_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['type']},
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effects', models.ManyToManyField(to='game.Effect', verbose_name='Effects')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.itemtype')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.rarity')),
            ],
            options={
                'verbose_name_plural': 'Add-Ons',
            },
        ),
    ]
