# Generated by Django 3.1.3 on 2020-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='type',
            field=models.CharField(choices=[('Survivor', 'Survivor'), ('Killer', 'Killer'), ('All', 'All')], default='All', max_length=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to='characters'),
        ),
    ]
