# Generated by Django 3.1.3 on 2020-11-14 19:53

from django.db import migrations, models
import game.models.character


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201113_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to=game.models.character.character_directory_path),
        ),
    ]
