# Generated by Django 3.1.3 on 2020-11-14 21:30

from django.db import migrations, models
import game.models.character
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201114_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.character.character_directory_path),
        ),
    ]
