# Generated by Django 3.1.3 on 2020-11-14 21:38

from django.db import migrations, models
import game.models.perk
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201114_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.perk.perk_directory_path),
        ),
    ]
