# Generated by Django 3.1.3 on 2020-11-14 21:53

from django.db import migrations, models
import game.models.offering
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_perk_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.offering.offering_directory_path),
        ),
    ]
