# Generated by Django 3.1.3 on 2020-11-14 22:54

from django.db import migrations, models
import django.db.models.deletion
import game.models.power
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20201114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.power.power_directory_path)),
                ('effects', models.ManyToManyField(to='game.Effect', verbose_name='Effects')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='itemaddon',
            old_name='item_type',
            new_name='type',
        ),
        migrations.CreateModel(
            name='PowerAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effects', models.ManyToManyField(to='game.Effect', verbose_name='Effects')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.power')),
                ('rarity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.rarity')),
            ],
            options={
                'verbose_name': 'Power Add-On',
                'verbose_name_plural': 'Power Add-Ons',
            },
        ),
    ]
