# Generated by Django 3.1.3 on 2020-11-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201114_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perk',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='power',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
    ]
