# Generated by Django 3.1.3 on 2020-11-15 09:53

from django.db import migrations, models
import game.models.item
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20201114_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.item.overlay_directory_path),
        ),
    ]
