# Generated by Django 3.1.3 on 2020-11-15 10:02

from django.db import migrations, models
import game.models.add_on
import game.models.offering
import game.models.power
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_item_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaddon',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.add_on.overlay_item_directory_path),
        ),
        migrations.AddField(
            model_name='offering',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.offering.overlay_directory_path),
        ),
        migrations.AddField(
            model_name='power',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), 
            upload_to=game.models.power.primary_overlay_directory_path),
        ),
        migrations.AddField(
            model_name='poweraddon',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.add_on.overlay_power_directory_path),
        ),
    ]
