# Generated by Django 3.1.3 on 2020-11-15 10:07

from django.db import migrations, models
import game.models.perk
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20201115_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.perk.overlay_directory_path),
        ),
    ]
