# Generated by Django 3.1.3 on 2020-11-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='addons',
        ),
        migrations.AlterField(
            model_name='player',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_addons',
            field=models.ManyToManyField(blank=True, null=True, to='game.ItemAddOn'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.power'),
        ),
        migrations.AlterField(
            model_name='player',
            name='power_addons',
            field=models.ManyToManyField(blank=True, null=True, to='game.PowerAddOn'),
        ),
    ]
