# Generated by Django 3.1.3 on 2020-11-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_character_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_licensed',
            field=models.BooleanField(default=False),
        ),
    ]
