# Generated by Django 3.1.3 on 2020-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_character_is_licensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_licensed',
            field=models.BooleanField(default=False, verbose_name='Licensed Character?'),
        ),
    ]
