# Generated by Django 3.1.3 on 2020-11-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20201122_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='EXOUEM', max_length=6, unique=True)),
                ('mode', models.CharField(choices=[('Killer', 'Killer'), ('Survivor', 'Survivor'), ('Custom', 'Custom')], max_length=255)),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.map')),
                ('obsession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsession', to='game.player')),
                ('players', models.ManyToManyField(related_name='players', to='game.Player')),
            ],
        ),
    ]
