# Generated by Django 3.1.3 on 2020-11-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='game_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.map', verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='XPCN3P', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
