# Generated by Django 3.1.3 on 2020-11-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20201122_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Realm',
        ),
        migrations.RemoveField(
            model_name='session',
            name='game_map',
        ),
        migrations.AddField(
            model_name='session',
            name='realm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.realm', verbose_name='Realm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='4K96JU', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
