# Generated by Django 3.1.3 on 2020-11-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20201122_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_host',
        ),
        migrations.AddField(
            model_name='session',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='host', to='game.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='AEWY0F', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
