# Generated by Django 3.1.3 on 2020-11-22 11:05

from django.db import migrations, models
import game.models.realm
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20201122_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.realm.realm_directory_path),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='2IXUKK', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
