# Generated by Django 3.1.3 on 2020-11-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_auto_20201122_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='RY9OMQ84', max_length=8, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='realm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.realm', verbose_name='Realm'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='KRXHGI', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
