# Generated by Django 3.1.3 on 2020-11-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20201122_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.offering'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='7J9T01S5', max_length=8, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='obsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsession', to='game.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='UMFDFY', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
