# Generated by Django 3.1.3 on 2020-11-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_auto_20201122_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='PPE7YTHK', max_length=8, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.realm', verbose_name='Realm'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='AD24IJ', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
