# Generated by Django 3.1.3 on 2020-11-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_auto_20201122_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='BXRL8XW9', max_length=8, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='SVXGV4', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
