# Generated by Django 3.1.3 on 2020-11-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_auto_20201122_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='E0DG4DKP', max_length=8, unique=True, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='SP3SXG', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
