# Generated by Django 3.1.3 on 2020-11-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_auto_20201122_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='XN3CSLPA', max_length=8, unique=True, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='game.player', unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='PIRZ1V', max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
