# Generated by Django 3.1.3 on 2020-11-23 06:59

from django.db import migrations, models
import django.db.models.deletion
import game.models.player
import game.models.session


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_auto_20201122_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=game.models.player.generate_player_id, max_length=8, unique=True, verbose_name='Player ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='game.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=game.models.session.generate_session_id, max_length=6, unique=True, verbose_name='Session ID'),
        ),
    ]
