# Generated by Django 3.1.3 on 2020-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_auto_20201122_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['player_id']},
        ),
        migrations.AddField(
            model_name='power',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='game.Player'),
        ),
    ]
