# Generated by Django 3.1.3 on 2020-12-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_auto_20201219_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='overlay',
            new_name='primary_overlay',
        ),
    ]
