# Generated by Django 3.1.3 on 2020-12-20 20:07

from django.db import migrations, models
import game.models.power
import game.storage


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_power_secondary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='tertiary_image',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.power.tertiary_power_directory_path),
        ),
        migrations.AddField(
            model_name='power',
            name='tertiary_overlay',
            field=models.ImageField(blank=True, null=True, storage=game.storage.OverwriteStorage(), upload_to=game.models.power.tertiary_overlay_directory_path),
        ),
    ]
