# Generated by Django 3.1.3 on 2021-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_auto_20210111_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditiontype',
            options={'verbose_name': 'Condition Type'},
        ),
        migrations.AlterModelOptions(
            name='modifiertype',
            options={'verbose_name': 'Modifier Type'},
        ),
        migrations.AlterModelOptions(
            name='modifierunit',
            options={'verbose_name': 'Modifier Unit'},
        ),
        migrations.AlterField(
            model_name='effect',
            name='condition',
            field=models.ManyToManyField(blank=True, to='game.Condition'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='game.Modifier'),
        ),
    ]
