# Generated by Django 3.1.3 on 2021-01-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_auto_20210111_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='summary',
            new_name='description',
        ),
    ]
