# Generated by Django 3.1.3 on 2021-01-12 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_auto_20210111_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_charges',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Charges'),
        ),
    ]
