# Generated by Django 3.1.3 on 2021-02-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_item_base_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AlterField(
            model_name='player',
            name='perks',
            field=models.ManyToManyField(blank=True, to='game.Perk'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('Survivor', 'Survivor'), ('Killer', 'Killer')], max_length=15, null=True),
        ),
    ]
