# Generated by Django 3.1.3 on 2021-02-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_auto_20210213_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['type']},
        ),
    ]
