# Generated by Django 3.1.3 on 2021-02-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_auto_20210215_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='effects',
        ),
    ]
