# Generated by Django 3.1.3 on 2021-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0058_auto_20210317_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='item',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='item',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='offering',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='offering',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='perk',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='perk',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='power',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='power',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='poweraddon',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='poweraddon',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AddField(
            model_name='realm',
            name='patch_version',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Patch Version'),
        ),
        migrations.AddField(
            model_name='realm',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Wiki Page'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='effects',
            field=models.ManyToManyField(blank=True, null=True, to='game.Effect', verbose_name='Effects'),
        ),
        migrations.AlterField(
            model_name='itemaddon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemaddon',
            name='effects',
            field=models.ManyToManyField(blank=True, to='game.Effect', verbose_name='Effects'),
        ),
        migrations.AlterField(
            model_name='modifierunit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offering',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='effects',
            field=models.ManyToManyField(blank=True, to='game.Effect', verbose_name='Effects'),
        ),
        migrations.AlterField(
            model_name='power',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='effects',
            field=models.ManyToManyField(blank=True, null=True, to='game.Effect', verbose_name='Effects'),
        ),
        migrations.AlterField(
            model_name='poweraddon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poweraddon',
            name='effects',
            field=models.ManyToManyField(blank=True, to='game.Effect', verbose_name='Effects'),
        ),
    ]
