# Generated by Django 3.1.3 on 2021-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0059_auto_20210317_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effects',
            field=models.ManyToManyField(blank=True, to='game.Effect', verbose_name='Effects'),
        ),
        migrations.AlterField(
            model_name='power',
            name='effects',
            field=models.ManyToManyField(blank=True, to='game.Effect', verbose_name='Effects'),
        ),
    ]
