# Generated by Django 3.1.3 on 2021-03-20 05:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0060_auto_20210317_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='tiers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None), blank=True, null=True, size=3),
        ),
    ]
