# Generated by Django 3.1.3 on 2021-03-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_perk_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='rarities',
            field=models.ManyToManyField(blank=True, to='game.Rarity', verbose_name='Rarities'),
        ),
        migrations.AlterField(
            model_name='perk',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_rarity', to='game.rarity'),
        ),
    ]
