# Generated by Django 3.1.3 on 2021-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_auto_20210319_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
