# Generated by Django 3.1.3 on 2021-03-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_auto_20210319_2343'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='perk',
            name='perk_name_tier_key',
        ),
        migrations.RenameField(
            model_name='perk',
            old_name='quote',
            new_name='flavor',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='tier',
        ),
    ]
