# Generated by Django 3.1.3 on 2021-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0065_remove_perk_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaddon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='itemaddon',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='poweraddon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='poweraddon',
            name='rarity',
        ),
        migrations.AddField(
            model_name='itemaddon',
            name='rarities',
            field=models.ManyToManyField(blank=True, to='game.Rarity', verbose_name='Rarities'),
        ),
        migrations.AddField(
            model_name='poweraddon',
            name='rarities',
            field=models.ManyToManyField(blank=True, to='game.Rarity', verbose_name='Rarities'),
        ),
    ]
