# Generated by Django 3.1.3 on 2021-03-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0066_auto_20210320_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='power',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='power',
            name='secondary_image',
        ),
        migrations.RemoveField(
            model_name='power',
            name='tertiary_image',
        ),
        migrations.AddField(
            model_name='item',
            name='rarities',
            field=models.ManyToManyField(blank=True, to='game.Rarity', verbose_name='Rarities'),
        ),
        migrations.AddField(
            model_name='offering',
            name='rarities',
            field=models.ManyToManyField(blank=True, to='game.Rarity', verbose_name='Rarities'),
        ),
    ]
