# Generated by Django 3.1.3 on 2021-03-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0070_auto_20210320_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='image',
        ),
    ]
